myapp/urls.py
from django.urls import path
from . import views

app_name="myapp"

urlpatterns = [
    path("",views.home,name="home"),
    path("url/",views.index,name="index"),
    path("<str:key>/",views.sort_url,name="sort_url"),
]

urlsortner/urls.py
from django.contrib import admin
from django.urls import path,include
from . import urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("myapp.urls")),
]

myapp/models.py
from django.db import models

# Create your models here.


class LinkUrl(models.Model):
    link=models.CharField(max_length=1000)
    slug=models.CharField(max_length=10)

    def __str__(self) -> str:
        return self.link

myapp/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
import uuid
# Create your views here.
from .models import LinkUrl

def home(request):
    return render(request,"index.html")

def index(request):
    if request.method=="POST":
        link=request.POST["url"]
        obj1=LinkUrl.objects.filter(link=link)
        if obj1:
            return render(request,"index.html",{"context":"https://djangourlsortner.herokuapp.com/"+str(obj1[0].slug)})
        else:
            uid=str(uuid.uuid4())[:5]
            obj=LinkUrl(link=link,slug=uid)
            print(link)
            obj.save()
            return render(request,"index.html",{"context":"https://djangourlsortner.herokuapp.com/"+uid})
    else:
        return redirect("/home")
        
def sort_url(request,key):
    object=LinkUrl.objects.filter(slug=key)[0]
    return redirect(object.link)

myapp/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Url Sortner</title>
        <link  rel="stylesheet" href="{% static 'index.css' %}">
    </head>

<body>
    <div class="main-div">
        <div class="sub-div">
            <h1>Url Sortner</h1>
            <form method="POST" action="{% url 'myapp:index' %}" onsubmit="return validateForm()">
                {% csrf_token %}
                <input type="url" name="url" id="url" placeholder="Enter Url.."></br>
                <button type="submit" id="submit">Submit</button>
            </form>
            {% if context %}
            <p>Sort Url::<strong>{{ context }}</strong></p>
            {% endif %}
        </div>
    </div>

    <script src="{% static 'index.js' %}"></script>
</body>
</html>